Channel-related REST helpers and minor fixes.
Added following REST helpers:
* getChannel (not tested)
* modifyChannel (not tested)
* deleteChannel (not tested)
* getChannelMessages (not tested)
* getChannelMessage (not tested)
* sendMessages (without attachments and rich content support)
* editMessage (without rich content support)
* deleteMessage

Fixed compilation error caused by wrong implicit conversion from JSON at
client.cpp:44.

More robust error handling: now catches "internal" API errors.

Now APIError contains message field which contains original error
description. what() returns more complete message including API and HTTP
status codes.

Reconnect if gateway closed connection during message reading.

Fixed handling of empty response body in sendRestRequest.